language: python
install:
  - pip install -r requirements.txt
  - npm install -g newman
script:
  - FLASK_APP = server.py
  - flask run && newman run 'Scalez.postman_collection.json' --environment 'Development.postman_environment.json'
