language: python
install:
  - pip install -r requirements.txt
  - npm install -g newman
script:
  - export FLASK_APP=server.py
  - flask run  & sleep 10 && newman run 'Scalez.postman_collection.json' --environment 'Development.postman_environment.json'
