language: python
install:
  - pip install -r requirements.txt
  - npm install -g newman
script:
  -
  - newman run 'Scalez.postman_collection.json' --environment 'Development.postman_environment.json'
