language: python
install:
  - pip install -r requirements.txt
  - npm install -g newman
postgres:
  adapter: postgresql
  database: myapp_test
  username: postgres
before_script:
  - psql -c 'create database myapp_test;' -U postgres
  - export DATABASE_URL=postgresql://postgres:@localhost:5432/myapp_test
  - python db_create.py
services:
  - postgresql
script:
  - export FLASK_APP=server.py
  - flask run  & sleep 10 && newman run 'misc/Scalez.postman_collection.json' --environment 'misc/Development.postman_environment.json'

