# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Scalez' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Scalez
  pod 'CryptoSwift'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Alamofire', '~> 4.7'
  pod 'Charts'
  
  target 'ScalezTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ScalezUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
